---
cgit_url: https://yhbt.net/rainbows.git/
rdoc_url: https://yhbt.net/rainbows/
merge_html:
  rainbows_1: man/man1/rainbows.1.html
  Summary: Documentation/comparison.html
public_email: rainbows-public@yhbt.net
noindex:
- TODO
- LATEST
- Unicorn
- Unicorn::Configurator
- Unicorn::SocketHelper
- EM
- Revactor
ml_url:
- https://yhbt.net/rainbows-public/
- http://ou63pmih66umazou.onion/rainbows-public/
source_code:
- git clone https://yhbt.net/rainbows.git
- torsocks git clone http://ou63pmih66umazou.onion/rainbows.git
nntp_url:
- nntp://news.public-inbox.org/inbox.comp.lang.ruby.rainbows
- nntp://ou63pmih66umazou.onion/inbox.comp.lang.ruby.rainbows
- nntp://news.gmane.io/gmane.comp.lang.ruby.rainbows.general
